### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by markhughes** [emden-norfolk/cidrl#1]
Hello, thanks for making and sharing this! 

Does it support IPv6? Can it?

**Comment by dbezborodovrp** [comment]
Not at the moment. I suppose it could be done.

**Comment by bezborodow** [comment]
Useful functions: [inet_pton](https://man7.org/linux/man-pages/man3/inet_pton.3.html), [inet_ntop](https://man7.org/linux/man-pages/man3/inet_ntop.3.html)

**Comment by bezborodow** [comment]
@markhughes I have a rough version working now:

```
$ ./cidrl6 fa01::0000:0a10/124
fa01::a10
fa01::a11
fa01::a12
fa01::a13
fa01::a14
fa01::a15
fa01::a16
fa01::a17
fa01::a18
fa01::a19
fa01::a1a
fa01::a1b
fa01::a1c
fa01::a1d
fa01::a1e
fa01::a1f
```

**Comment by bezborodow** [comment]
Given the huge amount of hosts in an end-user network, I have reached the conclusion that what would be useful here is being able to list a bunch of /64 subnets within a CIDR block. Here is an example of this:

```console
$ cidrl6 -s64 fa01:0:0:ffa0::/60
fa01:0:0:ffa0::/64
fa01:0:0:ffa1::/64
fa01:0:0:ffa2::/64
fa01:0:0:ffa3::/64
fa01:0:0:ffa4::/64
fa01:0:0:ffa5::/64
fa01:0:0:ffa6::/64
fa01:0:0:ffa7::/64
fa01:0:0:ffa8::/64
fa01:0:0:ffa9::/64
fa01:0:0:ffaa::/64
fa01:0:0:ffab::/64
fa01:0:0:ffac::/64
fa01:0:0:ffad::/64
fa01:0:0:ffae::/64
fa01:0:0:ffaf::/64
```
